### ISSUE TITLE
Support python noarch packages

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/conda-smithy#485]
As of conda 4.3 we can make noarch packages for python libs as detailed in
https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages

There is an example of this in https://github.com/conda-forge/imagesize-feedstock/pull/3 . We probably want to support this kind of package for simpler pure python libraries that we want conda-forge package for.

**Comment by marscher** [comment]
@jakirkham What is the reason for conda-forge to still pin conda to 4.2? Noarch packages would be a great improvement and save a lot of CI time.

**Comment by jakirkham** [comment]
> Noarch packages would be a great improvement...

Indeed they would.

> What is the reason for conda-forge to still pin conda to 4.2?

We aren't actually pinning to `conda` 4.2. We just don't have `conda` 4.3. However we may need to start pinning some things to `conda` 4.2 if 4.3 is released on conda-forge.

The reason being `conda-build-all` is not compatible with `conda` 4.3 (see linked issue). Also I'm not sure if `conda-smithy` is compatible with `conda` 4.3, but it depends on `conda-build-all`. So it sort of doesn't matter until we can fix `conda-build-all`.

To date I don't think anyone has had time to push forward on that issue. If you have time to look, we would certainly appreciate the effort. At a bare minimum seeing the test failures for `conda-build-all` when using `conda` 4.3 will already be very helpful and shouldn't be too difficult as it will amount to adding a matrix item to their CI.

xref: https://github.com/SciTools/conda-build-all/issues/76

**Comment by jakirkham** [comment]
For reference, `conda-build-all` fix for `conda` 4.3 proposed in PR ( https://github.com/SciTools/conda-build-all/pull/83 ).

**Comment by Korijn** [comment]
Seeing as this issue would represent moving towards noarch packages on conda-forge, I have a bit of a fundamental question. What exactly is the certainty that, this time around, noarch packages will _remain_ supported? Last time they were introduced they broke a bunch of times and that got us into a lot of headaches, since we were pretty invested into noarch... we've since stopped using the feature completely out of fear that it will break again.

**Comment by marscher** [comment]
I think they have done it right, this time. Was the last feature also advertised like [this](https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages)? As you see from the blog post, Continuum A. has already started to use the new feature in their recipes, so I'd doubt that this time they would abandon it again in the near future.

**Comment by marscher** [comment]
Mhm, no there is no evidence they're using it already. Sorry for the false claim

**Comment by jjhelmus** [comment]
There are a few `noarch` packages in the `defaults` repository, https://repo.continuum.io/pkgs/free/noarch/, but they are not widely used yet.  

I would be in favor of moving conda-forge to noarch packages when appropriate.  I have been using these packages in [berryconda](https://github.com/jjhelmus/berryconda) and other than a few initial issues with entry points they seem to be working well.

**Comment by marscher** [comment]
the preparations for conda-4.3 are almost done, I think.

**Comment by jakirkham** [comment]
Right now we don't have a working `conda` on Windows. So not quite.

Also need to fix more tooling that `conda` affects. Namely `conda-execute` is not `conda` 4.3 compatible. Am debating the merits of forking `conda-execute` for conda-forge to fix this.

**Comment by jjhelmus** [comment]
I've created PRs for `conda-smithy` and `conda-build-all` to better support `noarch: python` recipe.  See conda-forge/conda-smithy#531 aand conda-forge/conda-build-all#6.

**Comment by jakirkham** [comment]
Thanks for doing that @jjhelmus.

Just reviewed the `conda-smithy` one. That looks pretty healthy, but could use some tests. After that we can get it merged.

The `conda-build-all` one may take some more thought.

**Comment by jakirkham** [comment]
I don't think this is a concern, but wanted to raise it just in case. Are there any tweaks we need to make to the upload script to handle `noarch: python` packages?

**Comment by jakirkham** [comment]
Also have not kept up with this as much as I should. Is `noarch_python` still a thing? Will it still be a thing? What differs between it an `noarch: python`? Is `noarch_python` something we should be trying to support as well?

**Comment by mariusvniekerk** [comment]
I believe that the other variant is deprecated

**Comment by Korijn** [comment]
There are three cases now. Omitted, `python`, and `generic`. I think one of the two is legacy mode?

**Comment by jakirkham** [comment]
Done in PRs ( https://github.com/conda-forge/conda-build-all/pull/9 ) and ( https://github.com/conda-forge/conda-smithy/pull/531 ). Thanks to @jjhelmus and @isuruf for their hard work on this.

**Comment by jschueller** [comment]
So we still cannot push noarch packages on conda-forge to save ci time ?

**Comment by jakirkham** [comment]
What do you mean? `noarch` is now supported. Is there a particular issue you are having?

**Comment by jschueller** [comment]
yes, I added noarch_python, no changes on rerendering

**Comment by jschueller** [comment]
oh, it's just 'noarch', my bad

**Comment by jakirkham** [comment]
Yeah we discussed supporting `noarch_python` as well and decided against it as it was deprecated/had issues. So we only supported the newer `noarch: python`.
